### ISSUE TITLE
STAN package is deprecated

### ISSUE THREAD

**Issue by ljharrison** [shaorray/TU_filter#4]
Hi, I'm very keen to use your shiny app, but I am having issues with the package STAN. I am using R version 4.3.1 with Bioconductor 3.17. When I try to run the app I get the following warning:

`Warning: package ‘STAN’ is not available for this version of R`

When looking at the [Bioconductor website ](https://bioconductor.org/packages/release/bioc/html/STAN.html), it says that STAN is deprecated and likely to be removed from Bioconductor. Is there a work-around for this issue? Would this work in an older version of R and/or Bioconductor?

Thanks in advance!

**Comment by shaorray** [comment]
Thanks for reporting this issue. Now STAN source package is uploaded in the main directory.

Dependency `poilog` and `Rsolnp` can be install from CRAN. ~
