### ISSUE TITLE
TU Filter error

### ISSUE THREAD

**Issue by aswathyseb** [shaorray/TU_filter#5]
Hi,

I am running TU filter and at the TU calling step, I get the following

`Warning: Error in [[<-: 1 elements in value to replace 0 elements`

Could you help me understand what the problem is?

I am using R version 4.2.3.

Thanks,

**Comment by shaorray** [comment]
Thanks for reporting the error, it could be the same as issue #4. TU filter depends on 'GenoSTAN' package, which is out of bioconductor's maintenance. 

Please make sure `STAN` package is installed, or reinstall the archived version uploaded in **main**.

**Comment by aswathyseb** [comment]
I am reopening this issue as I don't think it is related to STAN.

I do have STAN (v 2.26.2) installed and I was able to run a stand-alone STAN script.

I have attached the session info here.

What else do you think might be the problem?  I would like to see the app running.

Thanks,
[sessionInfo.txt](https://github.com/shaorray/TU_filter/files/14117526/sessionInfo.txt)
